### ISSUE TITLE
Unpublished dependency hex_plugin

### ISSUE THREAD

**Issue by jespersm** [PhaestusFox/bevy_wave_collapse#1]
Hi PhaestusFox
Neat video, but when I tried using the plugin, I hit the missing dependency 'hex_plugin'. Is that something which you'll be publishing?

**Comment by PhaestusFox** [comment]
ah sorry about that, I was using my hex_plugin for some tests and forgot that is it not public, at least not yet, the idea is for bevy_wave_collapse to be self-standing without the need to be fixed to  a specific may system so I am working or removing the dependence on that crate and just copying what it needs into the bench.rs
